-- MySQL Script generated by MySQL Workbench
-- dom 04 oct 2020 15:49:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ms_user_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ms_user_db` ;

-- -----------------------------------------------------
-- Schema ms_user_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_user_db` ;
USE `ms_user_db` ;

-- -----------------------------------------------------
-- Table `ms_user_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_user_db`.`user` ;

CREATE TABLE IF NOT EXISTS `ms_user_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `career` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `name` VARCHAR(80) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_user_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ms_user_db`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_user_db`.`note` ;

CREATE TABLE IF NOT EXISTS `ms_user_db`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note_content` LONGTEXT NULL,
  `id_user` INT NOT NULL,
  UNIQUE INDEX `idNote_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `ms_user_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ms_user_db`.`note_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_user_db`.`note_access` ;

CREATE TABLE IF NOT EXISTS `ms_user_db`.`note_access` (
  `id_note` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_note_access_2_idx` (`id_user` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_pair` (`id_note` ASC) VISIBLE,
  CONSTRAINT `note_access_note`
    FOREIGN KEY (`id_note`)
    REFERENCES `ms_user_db`.`note` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `note_access_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `ms_user_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
